<?php
  $voitures = ["0" =>
              ["modele" => "Porsche Panamera", "type" => "v6 GTS", "image" => "img/porsche-panamera-2017.jpg", "details" => "Lancée en 2009, La Panamera était, jusqu'à peu, disponible en 8 versions depuis le seuil d'accès 6 cylindres 300 chevaux jusqu'au modèle Turbo S V8 de 550 chevaux en passant par des variantes diesel et hybride de 250 et 380 chevaux. Avec la GTS (Gran Turismo Sport), Porsche propose la quintessence sportive de la gamme sans avoir recours à la suralimentation. Avec à la clé des performances pures et authentiques rappelant celles de la 904 Carrera de 1963, la première Porsche GTS de l'histoire. Redoutable sur la route et fascinante dans sa présentation, la GTS bénéficie d'un châssis surbaissé, de freins renforcés et d'une stupéfiante suspension pneumatique à la carte la rendant confortable même avec les jantes optionnelles Turbo II de 20 pouces. A cette avalanche de plus technologiques s'ajoutent une transmission intégrale quasi parfaite et une boite PDK double embrayage 7 rapports."],
              "1" =>
              ["modele" => "Porsche Macan", "type" => "GTS 340ch", "image" => "img/porsche-macan_gts-1.jpg", "details" => "Cela fait 12 ans déjà que Porsche a franchi le Rubicond en lançant le Cayenne de première génération. Un mouvement qui avait fait polémique à l'époque : la marque de Zuffenhausen n'allait-elle pas vendre son âme au diable et dégrader son image en se lançant sur le marché du SUV ? Mais les prédictions des Cassandre se sont révélées fausses : force est de reconnaître que Porsche ne s'est jamais aussi bien porté. La marque a dégagé pas moins de 2,58 milliards d'euros de bénéfices en 2013, tandis que les ventes ont atteint un niveau record : 162 145 immatriculations... dont un peu plus de la moitié de Cayenne. Porsche n'est donc déjà plus un constructeur de coupés sportifs, mais est bel et bien un acteur majeur du SUV haut de gamme."],
              "2" =>
              ["modele" => "Ferrari 488", "type" => "SPIDER 670ch", "image" => "img/ferrari-488_spider.jpg", "details" => "La Ferrari 488 GTB succombe donc elle aussi au charme du moteur turbocompressé. Dites adieu au moteur V8 4.5 L 610 ch de la Ferrari 458 Speciale et bonjour au nouveau moteur V8 3,8 L turbocompressé de 670 ch. Selon Ferrari, il s’agit d’un nouveau chapitre qui s’ouvre dans l’histoire des moteurs 8 cylindres puisque malgré le passage au turbo, la marque au cheval cabré promet un plaisir de conduite aussi exceptionnel et une expérience similaire à un moteur atmosphérique. Le temps de réponse à l’accélérateur est annoncé en à peine 0,8 secondes à 2 000 tr / min."],
              "3" =>
              ["modele" => "Mercedes G63", "type" => "AMG 571ch", "image" => "img/mercedes-g63_amg_1.jpg", "details" => "Mercedes vient de dévoiler son Classe G restylé. Celui-ci ne change que très peu extérieurement, et gagne notamment de nouveaux boucliers, de nouvelles jantes de 18 pouces à cinq rayons, mais surtout une nouvelle palette de couleurs. Mais c'est surtout sous le capot que l'on trouve les plus importants changements. Ainsi, la version G500 reçoit désormais le nouveau moteur V8 biturbo de 4,0 litres de la marque, qui alimente notamment le concept 4x4² G500 et produit 422 ch pour 610 Nm de couple, entre 2.250 et 4.750 tours par minute. Cela permet au G500 d'abattre le 0 à 100 km/h en 5,9 secondes."],
              "4" =>
              ["modele" => "Audi R8", "type" => "v10 610ch", "image" => "img/audi-r8-v10-1.jpg", "details" => "Faisant suite, après trois ans de développement, au concept-car Le Mans, la R8, alias Typ42, est devenue en 2006 à Paris la première GT badgée Audi. Une vraie révolution industrielle et un coup magistral pour doper l'image de marque en venant concurrencer Porsche et sa mythique 911. Le succès étant au rendez-vous, on lui accorda rapidement le droit d'utiliser le très exclusif V10 développé pour la Lamborghini Gallardo, dont elle partageait en très grande partie les dessous. L'Audi R8 V10 mettait ainsi un pied chez les supercars en venant chasser sur les terres de Ferrari, Aston Martin, Porsche et Lamborghini. Déclinée dans une ébouriffante version Spyder, c'est ainsi qu'elle nous avait laissé un souvenir mémorable."],
              "5" =>
              ["modele" => "Lamborghini HURACAN", "type" => "SPYDER 610ch", "image" => "img/lamborghini-huracan-spyder.jpg", "details" => "La Floride pour le taureau de Modène. Le constructeur transalpin a choisi Miami pour présenter sa nouvelle Huracan Spyder. Et ce n'est pas un hasard, puisque c'est dans un environnement où l'hiver n'a pas d'emprise que cette version se fond le mieux. L'Huracan LP 610-4 Spyder vient définitivement décoiffer son ainée, la Gallardo éponyme, avec de fortes prétentions. Elle adopte une capote souple hydraulique, contrairement à sa concurrente directe, la Ferrari 488 GTB Spider et son toit rigide rétractable. Un choix justifié par le constructeur pour limiter les coûts de développement et le poids du spyder, 1542 kg à sec. Cette capote, noir, brune ou rouge, selon l'humeur optionnelle, se plie ou se déplie en 17 secondes jusqu'à 50 km/h."]];

?>
